module Main where

import BasicFunctions
import HardwareTypes
import Sprockell
import System
import Simulation

prog0 :: [Instruction]
prog0 = [
          Load (ImmValue 0) regA, 
          Store regA (DirAddr 1), 
          Store reg0 (DirAddr 2), 
          Load (ImmValue 1) regB, 
          Push regB, 
          Load (ImmValue 5) regC, 
          Push regC, 
          Push reg0, 
          Load (ImmValue 11) regD, 
          Push regD, 
          Jump (Abs 46), 
          Pop reg0, 
          Pop regD, 
          Pop reg0, 
          Pop reg0, 
          I2I regD regE, 
          Load (ImmValue 10) regF, 
          Push regF, 
          Load (ImmValue 2) regG, 
          Push regG, 
          Push reg0, 
          Load (ImmValue 24) regH, 
          Push regH, 
          Jump (Abs 86), 
          Pop reg0, 
          Pop regH, 
          Pop reg0, 
          Pop reg0, 
          I2I regH regI, 
          Compute Add regE regI regJ, 
          Store regJ (DirAddr 1), 
          Load (ImmValue 0) regK, 
          Push regK, 
          Load (DirAddr 1) regL, 
          Push regL, 
          Push reg0, 
          Load (ImmValue 39) regM, 
          Push regM, 
          Jump (Abs 46), 
          Pop reg0, 
          Pop regM, 
          Pop reg0, 
          Pop reg0, 
          I2I regM regN, 
          Store regN (DirAddr 1), 
          EndProg, 
          Pop regO, 
          DecrSP, 
          Pop reg0, 
          Pop reg0, 
          Pop reg0, 
          Pop regP, 
          DecrSP, 
          DecrSP, 
          DecrSP, 
          DecrSP, 
          Branch regP (Abs 71), 
          Pop reg0, 
          Pop reg0, 
          Pop regQ, 
          DecrSP, 
          DecrSP, 
          DecrSP, 
          Load (ImmValue 0) regR, 
          Compute Sub regR regQ regR, 
          Pop regS, 
          Pop reg0, 
          Push regR, 
          Push reg0, 
          Jump (Ind regS), 
          Jump (Abs 84), 
          Pop reg0, 
          Pop reg0, 
          Pop regA1, 
          DecrSP, 
          DecrSP, 
          DecrSP, 
          Load (ImmValue 100) regB1, 
          Compute Add regA1 regB1 regC1, 
          Pop regD1, 
          Pop reg0, 
          Push regC1, 
          Push reg0, 
          Jump (Ind regD1), 
          Nop, 
          Jump (Ind regO), 
          Pop regE1, 
          DecrSP, 
          Pop reg0, 
          Pop reg0, 
          Pop regF1, 
          DecrSP, 
          DecrSP, 
          DecrSP, 
          Pop reg0, 
          Pop reg0, 
          Pop reg0, 
          Pop regG1, 
          DecrSP, 
          DecrSP, 
          DecrSP, 
          DecrSP, 
          Compute Mul regF1 regG1 regH1, 
          Pop regI1, 
          Pop reg0, 
          Push regH1, 
          Push reg0, 
          Jump (Ind regI1), 
          Jump (Ind regE1) 
       ] 
main = sysTest [prog0]